# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=real_estate.models.helper.get_file_path, verbose_name='изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='позиция')),
            ],
            options={
                'verbose_name': 'грамота',
                'verbose_name_plural': 'грамоты',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BankPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=real_estate.models.helper.get_file_path, verbose_name='изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='позиция')),
                ('title', models.CharField(max_length=127, verbose_name='название банка')),
            ],
            options={
                'verbose_name': 'объект банк-партнер',
                'verbose_name_plural': 'банки-партнеры',
                'ordering': ('position',),
            },
        ),
    ]
