# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=real_estate.models.get_file_path, verbose_name='изображение')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='позиция')),
            ],
            options={
                'verbose_name_plural': 'грамоты',
                'ordering': ['position'],
                'verbose_name': 'грамота',
            },
        ),
    ]
