# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 20:54
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import real_estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0005_auto_20180520_0154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleApartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='номер дома')),
                ('building_block', models.IntegerField(blank=True, help_text='оставьте пустым, если поле не имеет смысла', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='корпус')),
                ('zip_code', models.CharField(blank=True, max_length=127, null=True, verbose_name='почтовый индекс')),
                ('coordinates', models.CharField(blank=True, max_length=127, null=True, verbose_name='широта,долгота')),
                ('layout', models.ImageField(upload_to=real_estate.models.get_file_path, verbose_name='планировка')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('15.00'))], verbose_name='общая площадь (м2)')),
                ('interior_decoration', models.CharField(choices=[('D', 'ремонт'), ('ED', 'евро ремонт'), ('F', 'чистовая'), ('SF', 'предчистовая'), ('P', 'улучшенная черновая'), ('UF', 'черновая')], default='UF', max_length=31, verbose_name='вид отделки')),
                ('price', models.DecimalField(decimal_places=0, default=1000000, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена, рб')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('celling_height', models.DecimalField(decimal_places=1, default=2.7, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('2.0'))], verbose_name='высота потолка (м)')),
                ('is_active', models.BooleanField(default=True, verbose_name='отображать на сайте')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('rooms', models.CharField(choices=[('B', 'студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', help_text='Если вы не нашли нужного пункта - обратитесь к администратору', max_length=1, verbose_name='количество комнат')),
                ('floor', models.CharField(default=1, max_length=127, verbose_name='этаж')),
                ('section', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='подъезд/секция')),
                ('kitchen_area', models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('5.00'))], verbose_name='площадь кухни (м2)')),
                ('balcony_area', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='площадь балкона (м2)')),
                ('building_type', models.CharField(choices=[('BRICK', 'кирпичный'), ('MONO', 'монолитный'), ('FRAME', 'каркасный'), ('PANEL', 'панельный'), ('MFRAME', 'монолитно-каркасный'), ('BPANEL', 'панельный-кирпичный'), ('RCBLOCK', 'блоки железобетоные'), ('SBLOCK', 'cиликатный блок')], default='MONO', max_length=127, verbose_name='исполнение дома')),
                ('number_of_storeys', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество этажей')),
                ('agency_price', models.DecimalField(decimal_places=0, default=1000000, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена с комиссией от агенства, рб')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.NeighbourhoodModel', verbose_name='район')),
                ('posted_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='разместил')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.StreetModel', verbose_name='улица')),
            ],
            options={
                'verbose_name': 'Объекты Вторички',
            },
        ),
        migrations.AlterUniqueTogether(
            name='resaleapartment',
            unique_together=set([('street', 'building', 'building_block')]),
        ),
    ]
