# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0010_residentalcomplex_number_of_buildings'),
        ('resale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resaleapartment',
            options={'verbose_name': 'объект вторичка', 'verbose_name_plural': 'вторички'},
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='residental_complex',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='new_buildings.ResidentalComplex', verbose_name='Жилой комплекс'),
        ),
        migrations.AlterUniqueTogether(
            name='resaleapartment',
            unique_together=set([]),
        ),
    ]
