# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 19:39
from __future__ import unicode_literals

import address.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaleapartment',
            name='agency_price_with_sales',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, help_text='Оставьте поле пустым, чтобы скидка не отображалась.Сюда включена комиссия агенства, отображается на сайте', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='стоимость со скидкой, рб'),
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='coordinates',
            field=address.models.CoordinateField(blank=True, max_length=127, null=True, verbose_name='широта,долгота'),
        ),
    ]
