# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resale', '0002_auto_20180520_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resaleapartment',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resale_resaleapartment_created', to=settings.AUTH_USER_MODEL, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='modified_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='resale_resaleapartment_modified', to=settings.AUTH_USER_MODEL, verbose_name='изменено'),
        ),
    ]
