# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 04:14
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_auto_20180612_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=real_estate.models.get_file_path, verbose_name='изображение')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'изображения',
                'verbose_name': 'изображение',
            },
        ),
        migrations.AlterModelOptions(
            name='resaleapartment',
            options={'verbose_name': 'объект вторичка', 'verbose_name_plural': 'объекты вторички'},
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='amount_of_owners',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество собственников'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='apartment_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='номер квартиры'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий/результат сделки'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='date_of_construction',
            field=models.DateField(blank=True, null=True, verbose_name='Год постройки дома'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='home_series',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='серия дома'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='previous_buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата предыдущей покупки/сделки по данной недвижимости'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='related_mortgage',
            field=models.CharField(blank=True, choices=[('sberbank', 'ПАО «Сбербанк России»'), ('vtb24', 'ВТБ (ПАО)'), ('zpsib', 'ПАО «Запсибкомбанк»'), ('absolut', 'АКБ «Абсолют Банк»'), ('otkretie', 'ПАО Банк «ФК Открытие»'), ('rosselhoz', 'АО «Россельхозбанк»'), ('transkapital', 'ПАО «ТРАНСКАПИТАЛБАНК»'), ('deltacredit', 'АО «КБ ДельтаКредит»'), ('norooturalsib', 'Банк УРАЛСИБ'), ('akbars', '«АК БАРС» Банк')], default=None, help_text='если находится в ипотеке', max_length=127, null=True, verbose_name='В ипотеке у'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='sold_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата продажи/завершения сделки'),
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'активна'), ('SOLD-BY-US', 'продано с помощью ДОМУС'), ('SOLD-BY-SMBD', 'продано без участия ДОМУС')], default='ACTIVE', max_length=127, verbose_name='статус сделки'),
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='agency_price',
            field=models.DecimalField(decimal_places=0, default=1000000, help_text='данная цена = цена от продавца + комиссия Домус', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена с комиссией от агенства, рб'),
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1000000, help_text='данная цена является той суммой\n, которую хочет получить продавец.      Не отображается на сайте.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена, рб'),
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='residental_complex',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='new_buildings.ResidentalComplex', verbose_name='жилой комплекс'),
        ),
        migrations.AddField(
            model_name='resaleapartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='resale.ResaleApartment'),
        ),
    ]
