# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 19:10
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0004_auto_20180616_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resaleapartment',
            options={'permissions': (('can_add_change_delete_all_resale', 'Иммет доступ к чужим данным по вторичке'),), 'verbose_name': 'объект вторичка', 'verbose_name_plural': 'объекты вторички'},
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='owner_name',
            field=models.CharField(default='Без имени', max_length=127, verbose_name='ФИО продавца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resaleapartment',
            name='owner_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79999999999', max_length=128, verbose_name='номер телефона продавца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1000000, help_text='данная цена является той суммой, которую хочет получить продавец.          Не отображается на сайте.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена, рб'),
        ),
    ]
