# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 19:43
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0007_address__building_block_set_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaleapartment',
            name='agency_price_with_sales',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, help_text='Оставьте поле пустым, чтобы скидка не отображалась. Сюда включена комиссия агенства, отображается на сайте', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='стоимость со скидкой, рб'),
        ),
        migrations.AlterField(
            model_name='resaleapartment',
            name='agency_price',
            field=models.DecimalField(decimal_places=0, default=1000000, help_text='сюда включена комиссия агенства, отображается на сайте', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='начальная стоимость, рб'),
        ),
    ]
