# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 20:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='номер дома')),
                ('building_block', models.IntegerField(blank=True, help_text='оставьте пустым, если поле не имеет смысла', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='корпус')),
                ('zip_code', models.CharField(blank=True, max_length=127, null=True, verbose_name='почтовый индекс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeighbourhoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='название района')),
            ],
            options={
                'verbose_name_plural': 'районы',
                'verbose_name': 'район',
            },
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='улица')),
            ],
            options={
                'verbose_name_plural': 'улицы',
                'verbose_name': 'улица',
            },
        ),
        migrations.AddField(
            model_name='abstractaddressmodel',
            name='neighbourhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.NeighbourhoodModel', verbose_name='район'),
        ),
        migrations.AddField(
            model_name='abstractaddressmodel',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.StreetModel', verbose_name='улица'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractaddressmodel',
            unique_together=set([('street', 'building', 'building_block')]),
        ),
    ]
