# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourhoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='название района')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'районы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='улица')),
            ],
            options={
                'verbose_name': 'улица',
                'verbose_name_plural': 'улицы',
                'ordering': ('name',),
            },
        ),
    ]
