# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractaddressmodel',
            name='coordinates',
            field=models.CharField(blank=True, editable=False, max_length=127, null=True),
        ),
    ]
