# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20180218_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhoodmodel',
            options={'ordering': ('name',), 'verbose_name': 'район', 'verbose_name_plural': 'районы'},
        ),
        migrations.AlterModelOptions(
            name='streetmodel',
            options={'ordering': ('name',), 'verbose_name': 'улица', 'verbose_name_plural': 'улицы'},
        ),
    ]
