# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=127, verbose_name='улица')),
                ('building', models.IntegerField(verbose_name='дом')),
                ('building_block', models.IntegerField(blank=True, null=True, verbose_name='корпус')),
                ('zip_code', models.CharField(blank=True, max_length=127, null=True, verbose_name='почтовый индекс')),
            ],
            options={
                'verbose_name_plural': 'адреса',
                'verbose_name': 'адрес',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.IntegerField(verbose_name='квартира')),
                ('rooms', models.CharField(choices=[('B', 'студия'), ('B', '1'), ('B', '2'), ('B', '3'), ('B', '4')], default='1', max_length=1, verbose_name='количество комнат')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='этаж')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='real_estate.Address', verbose_name='адрес')),
            ],
            options={
                'verbose_name_plural': 'квартиры',
                'verbose_name': 'квартира',
            },
        ),
        migrations.CreateModel(
            name='ResidentalComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='название')),
                ('active', models.BooleanField(default=False, verbose_name='отображать в новостройках')),
            ],
            options={
                'verbose_name_plural': 'жилые комплексы',
                'verbose_name': 'жилой комплекс',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='residental_complex',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='real_estate.ResidentalComplex', verbose_name='ЖК'),
        ),
    ]
