# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 17:36
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='residental_complex',
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'квартиры', 'verbose_name_plural': 'квартиры'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='address',
        ),
        migrations.AddField(
            model_name='apartment',
            name='celling_height',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('2.0'))], verbose_name='высота потолка (м)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(default='asdas', verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='interior_decoration',
            field=models.CharField(choices=[('D', 'ремонт'), ('ED', 'евро ремонт'), ('F', 'чистовая'), ('SF', 'предчистовая'), ('P', 'улучшенная черновая'), ('UF', 'черновая')], default='UF', max_length=31, verbose_name='вид отделки'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='доступно на рынке'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='posted_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='разместил'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1000000, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='цена, рб'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='общая площадь (м2)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_number',
            field=models.IntegerField(verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.CharField(choices=[('B', 'студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', help_text='Если вы не нашли нужного пункта - обратитесь к администратору', max_length=1, verbose_name='количество комнат'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ResidentalComplex',
        ),
    ]
