# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import real_estate.models.helper


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateuser',
            name='bio',
            field=models.TextField(blank=True, max_length=255, verbose_name='биография'),
        ),
        migrations.AddField(
            model_name='realestateuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, verbose_name='отчество'),
        ),
        migrations.AddField(
            model_name='realestateuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='Будет отображаться на сайте при определенных настройках', upload_to=real_estate.models.helper.get_file_path, verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestateuser',
            name='show_at_company_page',
            field=models.BooleanField(default=True, help_text='Показывать ли контакт на странице с контактами компании и на прочих страницах, где это уместно?', verbose_name='Отображать на сайте'),
        ),
        migrations.AlterField(
            model_name='realestateuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='realestateuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='realestateuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='realestateuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterModelTable(
            name='realestateuser',
            table=None,
        ),
    ]
