# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 21:38
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0002_add_extra_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateGroup',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name_plural': 'группы',
                'verbose_name': 'группа',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
