# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_realestategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateuser',
            name='show_email',
            field=models.BooleanField(default=True, help_text='Показывать ли личный email на сайте?В противном случае будет показан email компании', verbose_name='Отображать email на сайте'),
        ),
        migrations.AddField(
            model_name='realestateuser',
            name='show_phone_number',
            field=models.BooleanField(default=True, help_text='Показывать ли личный номер на сайте?В противном случае будет показан номер компании', verbose_name='Отображать номер телефона на сайте'),
        ),
        migrations.AlterField(
            model_name='realestateuser',
            name='show_at_company_page',
            field=models.BooleanField(default=True, help_text='Показывать ли контакт на странице с контактами компании и на прочих страницах, где это уместно?', verbose_name='Отображать профиль на сайте'),
        ),
    ]
