# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название соц сети')),
                ('symbol', models.CharField(blank=True, max_length=256, verbose_name='символ в кодировке шрифтов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_media_links', verbose_name='иконка')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='порядок при стандартной сортировке')),
            ],
            options={
                'verbose_name': 'тип соц сети',
                'verbose_name_plural': 'типы соц сетей',
                'ordering': ['position'],
            },
        ),
    ]
