# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models.helper


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=real_estate.models.helper.get_file_path, verbose_name='логотип компании'),
        ),
        migrations.AlterField(
            model_name='residentalcomplexfeature',
            name='image',
            field=models.ImageField(upload_to=real_estate.models.helper.get_file_path, verbose_name='изображение'),
        ),
    ]
