# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentalcomplex',
            name='front_image',
            field=models.ImageField(default=None, upload_to=real_estate.models.get_file_path, verbose_name='Основное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeofcomplex',
            name='name',
            field=models.CharField(help_text='Необходимо писать в нижнем регистре. Преобразование к верхнему регистру происходит автоматически', max_length=127, unique=True, verbose_name='тип комплекса'),
        ),
    ]
