# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbuilding',
            name='coordinates',
            field=models.CharField(blank=True, editable=False, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='building_type',
            field=models.CharField(choices=[('BRICK', 'кирпичный'), ('MONO', 'монолитный'), ('FRAME', 'каркасный'), ('PANEL', 'панельный'), ('MFRAME', 'монолитно-каркасный'), ('BPANEL', 'панельный-кирпичный'), ('RCBLOCK', 'блоки железобетоные'), ('SBLOCK', 'cиликатный блок')], default='MONO', max_length=127, verbose_name='исполнение дома'),
        ),
    ]
