# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:01
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0002_building_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ГП', max_length=127, verbose_name='имя дома')),
                ('building_type', models.CharField(choices=[('BRICK', 'кирпичный'), ('MONO', 'монолитный'), ('FRAME', 'каркасный'), ('PANEL', 'панельный'), ('MFRAME', 'монолитно-каркасный'), ('BPANEL', 'панельный-кирпичный')], default='MONO', max_length=127, verbose_name='исполнение дома')),
                ('number_of_storeys', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество этажей')),
                ('date_of_construction', models.DateField(blank=True, help_text='Важно указать только месяц', null=True, verbose_name='дата постройки')),
                ('feed_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='ссылка на фид')),
            ],
            options={
                'verbose_name_plural': 'дома',
                'verbose_name': 'дом',
            },
        ),
        migrations.CreateModel(
            name='ResidentalComplexСharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='residental_complex',
        ),
        migrations.RenameField(
            model_name='builder',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='newapartment',
            name='balcony_area',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Если балкона нет - оставьте поле пустым', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='площадь балкона (м2)'),
        ),
        migrations.AddField(
            model_name='newapartment',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))], verbose_name='площадь кухни (м2)'),
        ),
        migrations.AddField(
            model_name='newapartment',
            name='section',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='подъезд/секция'),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='description',
            field=models.TextField(default='Desc', verbose_name='описание ЖК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='презентация ЖК'),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='добавлено'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='изменено'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='rooms',
            field=models.CharField(choices=[('B', 'студия'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', help_text='Если вы не нашли нужного пункта - обратитесь к администратору', max_length=1, verbose_name='количество комнат'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20.00'))], verbose_name='общая площадь (м2)'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='residental_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_buildings.ResidentalComplex', verbose_name='ЖК'),
        ),
        migrations.AddField(
            model_name='newapartment',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_buildings.NewBuilding', verbose_name='строение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='characteristics',
            field=models.ManyToManyField(to='new_buildings.ResidentalComplexСharacteristic', verbose_name='характеристики ЖК'),
        ),
    ]
