# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0002_auto_20171101_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentalcomplexfeature',
            options={'verbose_name': 'особенность комплекса', 'verbose_name_plural': 'особенности комплекса'},
        ),
        migrations.AlterModelOptions(
            name='residentalcomplexсharacteristic',
            options={'verbose_name': 'характеристика комплекса', 'verbose_name_plural': 'характеристики комплексов'},
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='number_of_flats',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='количество квартир в комплекск'),
        ),
        migrations.AlterField(
            model_name='residentalcomplexсharacteristic',
            name='icon',
            field=models.ImageField(upload_to=real_estate.models.get_file_path, verbose_name='иконка'),
        ),
    ]
