# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0003_auto_20171016_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builder',
            options={'verbose_name': 'застройщик', 'verbose_name_plural': 'застройщики'},
        ),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='characteristics',
            field=models.ManyToManyField(null=True, to='new_buildings.ResidentalComplexСharacteristic', verbose_name='характеристики ЖК'),
        ),
    ]
