# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models

from uuslug import slugify


def create_slug(apps, schema_editor):
    ResidentalComplex = apps.get_model("new_buildings", "ResidentalComplex")
    for rc in ResidentalComplex.objects.all():
        rc.slug = slugify(rc.name)
        rc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0003_change_coords_and_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentalcomplex',
            options={'ordering': ('-id', '-is_popular'), 'verbose_name': 'комплекс', 'verbose_name_plural': 'комплексы'},
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='slug',
            field=models.SlugField(
                allow_unicode=True,
                max_length=127,
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            create_slug, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='slug',
            field=models.SlugField(
                allow_unicode=True,
                max_length=127,
                unique=True,
                verbose_name='строка запроса',
            ),
        ),
    ]
