# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0003_auto_20171102_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentalcomplex',
            name='building_permit',
            field=models.FileField(blank=True, default=None, null=True, upload_to=real_estate.models.get_file_path, verbose_name='разрешение на строительство'),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='other_documents',
            field=models.FileField(blank=True, default=None, help_text='загрузите архив', null=True, upload_to=real_estate.models.get_file_path, verbose_name='остальные документы'),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='project_declarations',
            field=models.FileField(blank=True, default=None, help_text='загрузите архив', null=True, upload_to=real_estate.models.get_file_path, verbose_name='проектные декларации'),
        ),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='number_of_flats',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='количество квартир в комплексе'),
        ),
    ]
