# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0003_auto_20171211_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentalcomplex',
            name='building_permit',
        ),
        migrations.RemoveField(
            model_name='residentalcomplex',
            name='project_declarations',
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='building_permit',
            field=models.FileField(blank=True, default=None, null=True, upload_to=real_estate.models.get_file_path, verbose_name='разрешение на строительство'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='project_declarations',
            field=models.FileField(blank=True, default=None, null=True, upload_to=real_estate.models.get_file_path, verbose_name='проектная декларация'),
        ),
    ]
