# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models

from real_estate.utils import reorder


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0004_residentalcomplex_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentalcompleximage',
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='residentalcompleximage',
            name='position',
            field=models.PositiveIntegerField(
                default=0,
                verbose_name='позиция'),
        ),
        migrations.RunPython(
            lambda a, s: reorder(
                a, s, "new_buildings", "residentalcompleximage"),
            migrations.RunPython.noop
        ),
    ]
