# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0005_auto_20171225_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newapartment',
            options={'verbose_name': 'объект "планировка"', 'verbose_name_plural': 'планировки'},
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='buildings',
            field=models.ManyToManyField(to='new_buildings.NewBuilding', verbose_name='планировка присутсвует в домах'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='residental_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_buildings.ResidentalComplex', verbose_name='комплекс'),
        ),
    ]
