# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0005_auto_20171016_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbuilding',
            name='building',
            field=models.IntegerField(default=1, verbose_name='дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='building_block',
            field=models.IntegerField(blank=True, null=True, verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='city',
            field=models.CharField(choices=[('RU-TMN', 'Тюмень')], default='RU-TMN', max_length=127, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия')], default='RU', max_length=127, verbose_name='страна'),
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='neighbourhood',
            field=models.CharField(choices=[('MMS', 'ММС'), ('MYS', 'Мыс')], default='MMS', max_length=127, verbose_name='район'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='street',
            field=models.CharField(default='Первомайская', max_length=127, verbose_name='улица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newbuilding',
            name='zip_code',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='characteristics',
            field=models.ManyToManyField(blank=True, to='new_buildings.ResidentalComplexСharacteristic', verbose_name='характеристики ЖК'),
        ),
    ]
