# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models

from real_estate.templatetags.real_estate_extras import morphy_by_case


def resave_types_of_complex(apps, schema_editor):
    """ It resaves all type_of_complex objects to fill gent and loct fields"""
    typesofcomplex = apps.get_model("new_buildings", "typeofcomplex")
    for type_of_complex in typesofcomplex.objects.all():
        type_of_complex.gent = morphy_by_case(type_of_complex.name, 'gent')
        type_of_complex.loct = morphy_by_case(type_of_complex.name, 'loct')
        type_of_complex.save()


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0005_draggable_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofcomplex',
            name='gent',
            field=models.CharField(
                blank=True,
                help_text='Отвечает на вопросы: Кого, Чего? (комплекса)<br/>Определяется автоматически при первом сохранении.<br/>Измените, если автоматическое значение не подходит.',
                max_length=127,
                verbose_name='в родительном падеже'),
        ),
        migrations.AddField(
            model_name='typeofcomplex',
            name='loct',
            field=models.CharField(
                blank=True,
                help_text='Отвечает на вопросы: О ком, о чем? (О комплексе).<br/>Определяется автоматически при первом сохранении.<br/>Измените, если автоматическое значение не подходит.',
                max_length=127,
                verbose_name='в предложном падеже'),
        ),
        migrations.RunPython(
            resave_types_of_complex,
            reverse_code=migrations.RunPython.noop),
    ]
