# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0006_auto_20171016_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbuilding',
            name='active',
            field=models.BooleanField(default=True, verbose_name='показывать дом в новостройках'),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='date_of_construction',
            field=models.DateField(blank=True, help_text='Важен только месяц', null=True, verbose_name='дата постройки'),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='date_of_start_of_construction',
            field=models.DateField(blank=True, help_text='Важен только месяц', null=True, verbose_name='дата начала стройки'),
        ),
        migrations.AlterUniqueTogether(
            name='newbuilding',
            unique_together=set([('street', 'building', 'building_block')]),
        ),
    ]
