# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 22:30
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import real_estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0006_auto_20171225_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapartment',
            name='balcony_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='площадь балкона (м2)'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='floor',
            field=models.CharField(default=1, max_length=127, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='kitchen_area',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('5.00'))], verbose_name='площадь кухни (м2)'),
        ),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=real_estate.models.get_file_path, verbose_name='основное изображение'),
        ),
    ]
