# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0007_newapartment_decoration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newapartment',
            name='interior_decoration',
        ),
    ]
