# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 21:36
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0007_auto_20180106_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newapartment',
            options={'ordering': ('rooms',), 'verbose_name': 'объект "планировка"', 'verbose_name_plural': 'планировки'},
        ),
        migrations.AlterModelOptions(
            name='residentalcomplex',
            options={'ordering': ('-is_popular',), 'verbose_name': 'комплекс', 'verbose_name_plural': 'комплексы'},
        ),
        migrations.AlterField(
            model_name='newapartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('15.00'))], verbose_name='общая площадь (м2)'),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='coordinates',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='широта,долгота'),
        ),
    ]
