# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 20:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0008_auto_20180218_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapartment',
            name='date_of_construction',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='date_of_construction',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='residentalcomplex',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='newbuilding',
            name='number_of_storeys',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество этажей'),
        ),
    ]
