# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0010_residentalcomplex_number_of_buildings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentalComplexСharacteristic',
            new_name='ResidentalComplexCharacteristic',
        ),
        migrations.AlterField(
            model_name='typeofcomplex',
            name='name',
            field=models.CharField(help_text='Необходимо писать в нижнем регистре.             Преобразование к верхнему регистру происходит автоматически', max_length=127, unique=True, verbose_name='тип комплекса'),
        ),
    ]
