# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0011_auto_20180612_2018'),
        ('new_buildings', '0011_auto_20180715_2231'),
    ]

    operations = [
    ]
