# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0013_address__building_block_set_charfield'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='residentalcomplexcharacteristic',
            table='real_estate_residentalcomplexcharacteristic',
        ),
    ]
