# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_buildings', '0014_rename_characteristic'),
        ('real_estate', '0001_initial'),
    ]

    state_operations = [
        migrations.DeleteModel('ResidentalComplexCharacteristic'),
        migrations.CreateModel(
            name='ResidentalComplexCharacteristic',
            fields=[
            ],
            options={
                'verbose_name': 'характеристика комплекса',
                'verbose_name_plural': 'характеристики комплексов',
                'proxy': True,
                'indexes': [],
            },
            bases=('real_estate.characteristic',),
        ),
        migrations.AlterField(
            model_name='residentalcomplex',
            name='characteristics',
            field=models.ManyToManyField(
                blank=True,
                to='new_buildings.ResidentalComplexCharacteristic',
                verbose_name='характеристики ЖК'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
