# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='телефон')),
                ('url_from', models.URLField(verbose_name='источник заявки')),
                ('extra_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='дополнительная информация')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='время подачи')),
                ('promotion_context', models.CharField(blank=True, max_length=127, null=True, verbose_name='реклама')),
            ],
            options={
                'verbose_name': 'обратный звонок',
                'verbose_name_plural': 'заявки на обратный звонок',
            },
        ),
    ]
