# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import real_estate.models.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_buildings', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127, verbose_name='клиент')),
                ('date', models.DateField(blank=True, null=True, verbose_name='когда совершили сделку')),
                ('message', models.TextField(verbose_name='текст отзыва')),
                ('work_at', models.CharField(blank=True, max_length=127, null=True, verbose_name='место работы')),
                ('image', models.ImageField(upload_to=real_estate.models.helper.get_file_path, verbose_name='фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='отображать на сайте')),
                ('bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_buildings.ResidentalComplex', verbose_name='где купили')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SocialLinkForFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='отображаемый текст на ссылке')),
                ('url', models.CharField(max_length=4000, verbose_name='ссылка')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='заголовок тэга')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='feedback.Feedback', verbose_name='связанный отзыв')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.SocialLinkType', verbose_name='соц сеть')),
            ],
            options={
                'verbose_name': 'соц сеть',
                'verbose_name_plural': 'соц сети',
                'ordering': ['link_type__position'],
                'abstract': False,
            },
        ),
    ]
