# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='bought',
            new_name='residental_complex',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_resale',
            field=models.BooleanField(default=False, verbose_name='приобретено на вторичном рынке'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='residental_complex',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='new_buildings.ResidentalComplex', verbose_name='ЖК'),
        ),
    ]
