# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('feedback', '0002_auto_20171229_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkForFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='отображаемый текст на ссылке')),
                ('url', models.CharField(max_length=4000, verbose_name='ссылка')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='заголовок тэга')),
            ],
            options={
                'ordering': ['link_type__position'],
                'verbose_name_plural': 'соц сети',
                'verbose_name': 'соц сеть',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='когда совершили сделку'),
        ),
        migrations.AddField(
            model_name='sociallinkforfeedback',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='feedback.Feedback', verbose_name='связанный отзыв'),
        ),
        migrations.AddField(
            model_name='sociallinkforfeedback',
            name='link_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.SocialLinkType', verbose_name='соц сеть'),
        ),
    ]
